# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ecommerce' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ecommerce
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'ecommerce-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ecommerceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ecommerce-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
