# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ecommerce' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ecommerce
  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/DynamicLinks'

  target 'ecommerce-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  end

  target 'ecommerceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ecommerce-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
